version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: household
      POSTGRES_PASSWORD: household
      POSTGRES_DB: household_services
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U household -d household_services"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: 